### ISSUE TITLE
Transformer doesn't seem to link to the example

### ISSUE THREAD

**Issue by wsargent** [typesafehub/activator-akka-stream-scala#10]
There's a reference in the tutorial to `Transformer` and Flow, but in scaladsl2, Flow does not take Transformer.  In `scaladsl`, there's a reference to `Flow.transform()` but it's not clear how that connects, and there's no `Transformer` import.

https://github.com/typesafehub/activator-akka-stream-scala/blob/master/tutorial/index.html#L111

http://doc.akka.io/api/akka-stream-and-http-experimental/0.9/index.html#akka.stream.Transformer

**Comment by 2m** [comment]
Fixed in #23.
