### ISSUE TITLE
GroupLogFile example closes file too early

### ISSUE THREAD

**Issue by drewhk** [typesafehub/activator-akka-stream-scala#18]
It closes the file upon completion of the master stream, which has of course nothing to do with the completion of the individual groups writing (the master completes earlier). The proper solution is instead of using onComplete on the individual streams, just return the future, and call mapAsync(identity) on the master stream, and *then* register the onComplete(close()) call.

**Comment by 2m** [comment]
Closed after discussions in #19 and fix in #23.
